### ISSUE TITLE
ciasto marchewkowe, wegańskie (ale jajka są ok), pyszne

### ISSUE THREAD

**Issue by annprzy** [jkarolczak/ligands-classification#15]

**Comment by jkarolczak** [comment]
![img](https://thumbs.gfycat.com/BoldGrossBluefintuna-max-1mb.gif)

**Comment by reachfall** [comment]
> ![img](https://camo.githubusercontent.com/77a06e506ecb39ef2382d0d2a5dcdb072175f1f45fe742cb30ca8e066d4e86d8/68747470733a2f2f7468756d62732e6766796361742e636f6d2f426f6c6447726f7373426c756566696e74756e612d6d61782d316d622e676966)

Przecież nie ma nas na uczelni. Miałem wysłać pocztą?

**Comment by wtaisner** [comment]
jutro już jesteśmy na uczelni 😘

**Comment by jkarolczak** [comment]
GJ @reachfall
