### ISSUE TITLE
Find a network architecture

### ISSUE THREAD

**Issue by wtaisner** [jkarolczak/ligands-classification#17]

**Comment by jkarolczak** [comment]
https://paperswithcode.com/task/3d-object-classification

**Comment by dabrze** [comment]
The architectures in the link seem outside of the Sparse CNN category, but I might be wrong. It's important that the architecture is rotation invariant. My top runner before Michał suggested sparse CNNs was this: https://github.com/hkust-vgd/riconv

**Comment by MichalNowicki** [comment]
Some idea to extract features at different levels and concatenate them with Transformer (https://arxiv.org/abs/2105.11605)

**Comment by jkarolczak** [comment]
It relates to this topic and you are active here, so FYI: following our expert's suggestions after midterm presentations, we have checked PointNet. It wasn't a very demanding task as there is implementation provided by MinkowskiEngine authors that we only had to adjust to our data. If you are interested in results see run [#181](https://app.neptune.ai/o/LIGANDS/org/LIGANDS/e/LIGANDS-181/charts) in Neptune. You can compare it with run [#100](https://app.neptune.ai/o/LIGANDS/org/LIGANDS/e/LIGANDS-100/charts) (second best so far).

**Comment by MichalNowicki** [comment]
I am loosely following based on issues posted on github as there is not much progress shared in the slack. I do not have the access to neptune.ai -> add me as mnowicki and I will take a look.

**Comment by jkarolczak** [comment]
Final choice: [TransLoc3D](https://arxiv.org/pdf/2105.11605.pdf)
